export const FETCH_BLOGS_REQUEST = 'FETCH_BLOGS_REQUEST';
export const FETCH_BLOGS_SUCCESS = 'FETCH_BLOGS_SUCCESS';
export const FETCH_BLOGS_FAILURE = 'FETCH_BLOGS_FAILURE';

export const DELETE_BLOG_REQUEST = 'DELETE_BLOG_REQUEST';
export const DELETE_BLOG_SUCCESS = 'DELETE_BLOG_SUCCESS';
export const DELETE_BLOG_FAILURE = 'DELETE_BLOG_FAILURE';

export const UPDATE_BLOG_STATUS_REQUEST = 'UPDATE_BLOG_STATUS_REQUEST';
export const UPDATE_BLOG_STATUS_SUCCESS = 'UPDATE_BLOG_STATUS_SUCCESS';
export const UPDATE_BLOG_STATUS_FAILURE = 'UPDATE_BLOG_STATUS_FAILURE';
