export const FETCH_VIDEO_COURSES_REQUEST = 'FETCH_VIDEO_COURSES_REQUEST';
export const FETCH_VIDEO_COURSES_SUCCESS = 'FETCH_VIDEO_COURSES_SUCCESS';
export const FETCH_VIDEO_COURSES_FAILURE = 'FETCH_VIDEO_COURSES_FAILURE';
export const DELETE_VIDEO_COURSE_REQUEST = 'DELETE_VIDEO_COURSE_REQUEST';
export const DELETE_VIDEO_COURSE_SUCCESS = 'DELETE_VIDEO_COURSE_SUCCESS';
export const DELETE_VIDEO_COURSE_FAILURE = 'DELETE_VIDEO_COURSE_FAILURE';
